### ISSUE TITLE
I would like to see docker images and github actions

### ISSUE THREAD

**Issue by markussiebert** [timo-reymann/deterministic-zip#2]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I like this tool, because it solves a problem I have when building lambda functions for aws and only want to deploy them if anything changes - so deterministic builds are very helpful.

But it would be great, if there are docker images and github actions I can use :-)

I may be able to implement this, but are you interested in seeing this project?

**Comment by timo-reymann** [comment]
Hi @markussiebert,

first thank you for leaving your feedback. Always glad to hear when something I made helps others! 👍 

For CircleCI i already created an orb, so i would be also interested in the GitHub Action. If you already have some experience and feel able to implement it, i would gladly support you if there is anything coming up.

For the docker images part: I dont see a real use case here. Can you maybe elaborate further here which usecase/scenarios you see?

Cheers
Timo

**Comment by timo-reymann** [comment]
@markussiebert, @glenthomas there is now a docker image + GitHub action, so feel free to check it out and use it in your projects :)

**Comment by glenthomas** [comment]
> @markussiebert, @glenthomas there is now a docker image + GitHub action, so feel free to check it out and use it in your projects :)

Thanks @timo-reymann. It looks like the usage instructions [here](https://github.com/marketplace/actions/run-deterministic-zip) are incomplete as there is no `uses`.

I think it should be this:

```
    steps:
      - name: Build zip file
        uses: timo-reymann/deterministic-zip-gh-action
        with:
          source: .
          target: my-archive.zip
          # args: your additional arguments if required go here
```
