### ISSUE TITLE
[Bug]: bad zipfile offset 

### ISSUE THREAD

**Issue by antoineVIVIES** [timo-reymann/deterministic-zip#21]
### What happened?

I'm zipping a folder using: `deterministic-zip -r ../logs-extension-api.zip  . -x "*.rush/*" -x "*__tests__/*" -x "*.log"  -v`.
The zip is generated without issue, but when I do: `unzip ./logs-extension-api.zip` it says:
```
Archive:  ./logs-extension-api.zip
.rush/temp/operation/zip/state.json:  mismatching "local" filename (extensions-api.js),
         continuing with "central" filename version
  inflating: .rush/temp/operation/zip/state.json  
  error:  invalid compressed data to inflate
file #2:  bad zipfile offset (local header sig):  148
file #3:  bad zipfile offset (local header sig):  1028
file #4:  bad zipfile offset (local header sig):  4378
file #5:  bad zipfile offset (local header sig):  5210
file #6:  bad zipfile offset (local header sig):  5844
file #7:  bad zipfile offset (local header sig):  6663
file #8:  bad zipfile offset (local header sig):  7399
file #9:  bad zipfile offset (local header sig):  8076
file #10:  bad zipfile offset (local header sig):  8754
file #11:  bad zipfile offset (local header sig):  9311
file #12:  bad zipfile offset (local header sig):  9708
file #13:  bad zipfile offset (local header sig):  9846
file #14:  bad zipfile offset (local header sig):  10430
file #15:  bad zipfile offset (local header sig):  11177
file #16:  bad zipfile offset (local header sig):  22049
file #17:  bad zipfile offset (local header sig):  22374
file #18:  bad zipfile offset (local header sig):  23003
file #19:  bad zipfile offset (local header sig):  23383
```
I tried to remove the `-x` options and it works perfectly.

### OS

Darwin ARM

### Problem description

I think the repetition of -x options make a problem in the zip file

### Expected behaviour

Should unzip without issue

### Actual  behaviour

I got this error while unzip:
```
Archive:  ./logs-extension-api.zip
.rush/temp/operation/zip/state.json:  mismatching "local" filename (extensions-api.js),
         continuing with "central" filename version
  inflating: .rush/temp/operation/zip/state.json  
  error:  invalid compressed data to inflate
file #2:  bad zipfile offset (local header sig):  148
file #3:  bad zipfile offset (local header sig):  1028
file #4:  bad zipfile offset (local header sig):  4378
file #5:  bad zipfile offset (local header sig):  5210
file #6:  bad zipfile offset (local header sig):  5844
file #7:  bad zipfile offset (local header sig):  6663
file #8:  bad zipfile offset (local header sig):  7399
file #9:  bad zipfile offset (local header sig):  8076
file #10:  bad zipfile offset (local header sig):  8754
file #11:  bad zipfile offset (local header sig):  9311
file #12:  bad zipfile offset (local header sig):  9708
file #13:  bad zipfile offset (local header sig):  9846
file #14:  bad zipfile offset (local header sig):  10430
file #15:  bad zipfile offset (local header sig):  11177
file #16:  bad zipfile offset (local header sig):  22049
file #17:  bad zipfile offset (local header sig):  22374
file #18:  bad zipfile offset (local header sig):  23003
file #19:  bad zipfile offset (local header sig):  23383
```

### Steps to Reproduce

try to use the command with one or multiple `-x` flag

### I read and aggree to the contribution guidelines

- [X] I read and aggree to the contribution guidelines

**Comment by timo-reymann** [comment]
Heya, tried to reproduce a dummy file structure with the same names you provided, and not able to reproduce it :/

Can you maybe provide a git repository which can reproduce the error? Also which version are you using?

**Comment by antoineVIVIES** [comment]
Hey! 
Let me try to give you that, I'm using version 2.1.0.

**Comment by antoineVIVIES** [comment]
Hey, so far I didn't manage to reproduce the issue anymore sorry :/

However (different issue/question I can open another one), I saw that if there is a symlink (file or folder) in a folder you are trying to zip doesn't retrieve the file (zip does retrieve the file/folder associate).
Is it something you'll handle later or you're not planing to handle it ?
Thanks !

**Comment by timo-reymann** [comment]
Heya @antoineVIVIES,

okay, thanks for trying anyway, if the bug happens again feel free to reopen this issue or create a new one mentioning this.

For the symlink, that's simply currently not supported. You are welcome to create a feature request and I will have a look.

Cheers
Timo
