### ISSUE TITLE
Include directory entries in the zip file

### ISSUE THREAD

**Issue by nathanklick** [timo-reymann/deterministic-zip#3]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Due to the limitations of some zip implementations, it is sometimes necessary to include directory entries in the zip file. Additionally, in certain use cases an empty directory should be created when the zip file is extracted.  

### References

* https://bugs.python.org/issue34738

**Comment by nathanklick** [comment]
Pull request submitted: 
- #4

**Comment by timo-reymann** [comment]
Hi @nathanklick,

thanks for contributing. Changes look good so far but i will need to take a closer look everything still works etc.

As i am currently on vacation, i will do this around next week.

Cheers, Timo :)

**Comment by nathanklick** [comment]
@timo-reymann Hope you had a good vacation! Do you have an ETA on your thorough testing and review? If you accept these changes, would you mind cutting a new release version?

**Comment by timo-reymann** [comment]
Heya @nathanklick,

thank you! :)

I will review it until 29.08, maybe 28.08 if everything goes well.

After that i will create a new release :)

**Comment by timo-reymann** [comment]
Heya,

took a closer look at the changes. Merged it and released 1.2.0 :)
Thanks for contributing! 🥳 

Cheers
Timo

**Comment by nathanklick** [comment]
@timo-reymann Thank you for getting these changes  approved and a new release issued. We depend on this in several deployment CI pipelines and the lack of directory entries in the zip file was causing some pain for one of applications.
