### ISSUE TITLE
Add an option to recreate the archive if needed with -FS

### ISSUE THREAD

**Issue by charlesthobe** [timo-reymann/deterministic-zip#32]
### Description

Currently using `-FS` / `--filesync` appends the newly created files to the end of the archive which makes it non deterministic, having an extra option that deletes the archive and recreates it if needed would be nice to have.

**Comment by charlesthobe** [comment]
Also that option would preferably also check if the ordering of the added files is the same as if if would have been if the archive was created from scratch, and recreate the archive if the ordering is not the same.

**Comment by timo-reymann** [comment]
I am not quite sure what you are refering to. deteinistic-zip does not provide the arguments you mentioned. Also creates a file from Scratch everytime.

**Comment by charlesthobe** [comment]
Apologies, erroneous bug report.
