### ISSUE TITLE
no such file or directory (parity issue with regular zip)

### ISSUE THREAD

**Issue by TreeOfSelf** [timo-reymann/deterministic-zip#35]
### Description

When zipping with regular zip, you can name files/directories that don't exist, and it will simply print a message (that can be suppressed with -q) 

On deterministic-zip, if the file/directory doesn't exist it prints a message even with -q and won't zip at all.

**Comment by timo-reymann** [comment]
I was not aware of that difference. Working on it :)

**Comment by timo-reymann** [comment]
A bit hiccup with releasing, but is available with 3.0.0 :rocket: 

Thanks for pointing this out ☺️

**Comment by TreeOfSelf** [comment]
Thank you! deterministic-zip came in extremely clutch for the custom backup solution I am writing. Appreciate all of your work.
