### ISSUE TITLE
[Bug]: Zipping files in nested directories fails on Windows

### ISSUE THREAD

**Issue by eugenpodaru** [timo-reymann/deterministic-zip#37]
### What happened?

When using the tool on Windows with the options --recurse-paths and/or --directories, the included files and directories have mangled names as seen in the following image.

![Screenshot 2024-06-27 155030](https://github.com/timo-reymann/deterministic-zip/assets/1391294/3f096d1a-9ce9-4dc3-a8b3-afd7cab3cfe6)

### OS

Windows

### Problem description

The bug is easily reproductible on a Windows machine when trying to zip files/directories in nested sub-folders

### Expected behaviour

The names of the zip entries to correspond to the actual paths and names of the zipped files

### Actual  behaviour

The names of the zip entries are mangled with the path separator being replaced by an utf-8 character

### Steps to Reproduce

OS: Windows
Install: manual install by downloading the latest release binaries (the pipy package does not list Windows as a target)
Command: deterministic-zip package.zip . --recurse-paths --directories

### References

I am not a go developer, so I could not run or test the code locally, but just by looking at it, I found the bellow code which would be at least problematic on Windows. Not sure if it causes the issue.

https://github.com/timo-reymann/deterministic-zip/blob/f04ae03f0307955ab3480f3651f8533dd52e676e/pkg/zip/main.go#L95 

### I read and aggree to the contribution guidelines

- [x] I read and aggree to the contribution guidelines

**Comment by timo-reymann** [comment]
What command did you use to zip the file?

**Comment by eugenpodaru** [comment]
@timo-reymann thank you for fixing the issue! 

I would use it right away, but there are no binaries associated with the release tag.

Would it also be possible to also add Windows support in the wheel.yaml file?

**Comment by timo-reymann** [comment]
Ah sorry, my bad the release tag pipeline failed to codecov issues, checking and releasing 😅 

I can't really test the Windows version with Python, so I don't provide support for Windows in Wheels currently.

**Comment by timo-reymann** [comment]
Released with [3.0.1](https://github.com/timo-reymann/deterministic-zip/releases/tag/3.0.1)

**Comment by eugenpodaru** [comment]
@timo-reymann I tested, and it works. Thank you!
