### ISSUE TITLE
argument list too long

### ISSUE THREAD

**Issue by glenthomas** [timo-reymann/deterministic-zip#9]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Used versions

* Host OS: Darwin

## Problem description

Trying to zip some files, like this `deterministic-zip -D package.zip node_modules/**/*`

## Expected Behavior

Files are added to the zip

### Actual Behavior

I get this error
`zsh: argument list too long: deterministic-zip`

### References

* #0000

**Comment by timo-reymann** [comment]
Heya @glenthomas,

this is outside the scope of deterministic-zip, when you write `node_modules/**/*` in the zsh it will expand to a space separated argument list for the command you are calling.

To let deterministic-zip handle the expansion, simply quote the expression like this:

`deterministic-zip -D package.zip node_modules/**/*`

In your case, you can also save the glob pattern at all, by simply adding all files recursively, which is a good idea for node packages anyway:

`deterministic-zip -r package.zip node_modules`

**Comment by glenthomas** [comment]
Thanks @timo-reymann 👍

**Comment by glenthomas** [comment]
@timo-reymann , sorry to be a pain, but am hoping you can help me get this right...

I am trying to reproduce the following using deterministic-zip
```
zip -ur -oX deployment_package.zip node_modules/
cd .build
zip -r -oX ../deployment_package.zip .
```
So I want to add the node_modules directory and contents and then I want to add the contents of the .build directory. When I run deterministic-zip twice for the same package it overwrites the file rather than adding to it. What would be the correct arguments to do this in one deterministic-zip exec? Thanks

**Comment by timo-reymann** [comment]
Yes, to overwrite is intended behavior to make sure the file is always idempotent

As a workaround, you can do the following:

```shell
mkdir /tmp/build
cp -r node_modules .build /tmp/build
cd /tmp/build
deterministic-zip -r deployment_package.zip "*"
```

Which also makes sure changes won't change in between. If you just provide the .build folder, it will contain the folder prefix as well.
